# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
branches:
  only:
    - master
notifications:
  email: false

after_success:
  after_success:
  # deploy docs
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Dyn3d")); include(joinpath("docs", "make.jl"))'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Dyn3d")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Dyn3d")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
